name: Run Gulp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: gulp css
      run: |
        npm install
        npm install gulp-cli -g
        npm install gulp -D
        gulp css
    - name: Auto Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE = "Update CSS"
        COMMIT_AUTHOR_EMAIL  = "ee+gh@w3.org"
        COMMIT_AUTHOR_NAME = "Eric Eggert (auto)"
